# Generated by Django 5.1.5 on 2025-06-29 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stud_id', models.AutoField(primary_key=True, serialize=False)),
                ('stud_name', models.CharField(max_length=100)),
                ('stud_class', models.CharField(max_length=50)),
                ('stud_division', models.CharField(max_length=50)),
                ('stud_gender', models.CharField(max_length=10)),
                ('stud_contact', models.CharField(max_length=15)),
                ('stud_place', models.CharField(max_length=100)),
            ],
        ),
    ]
